const TargetProjectData = [
    {
      target: '102',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2568',
        endyear: '2580',
      },
      budget: 727619,
      own: 'ธพ.',
      plan: 'power',
      status: 1,
    },
    {
      target: '102',
      name: 'เร่งรัดการสำรวจและผลิตก๊าซธรรมชาติในประเทศ',
      year: {
        startyear: '2568',
        endyear: '2574',
      },
      budget: 1080739,
      own: 'ชธ.',
      plan: 'aedp',
      status: 0,
    },
    {
      target: '104',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2570',
        endyear: '2572',
      },
      budget: 1118412,
      own: 'สนพ.',
      plan: 'aedp',
      status: 2,
    },
    {
      target: '302',
      name: 'เร่งรัดการสำรวจและผลิตก๊าซธรรมชาติในประเทศ',
      year: {
        startyear: '2570',
        endyear: '2574',
      },
      budget: 211051,
      own: 'สนพ.',
      plan: 'gas',
      status: 2,
    },
    {
      target: '303',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2570',
        endyear: '2580',
      },
      budget: 1366713,
      own: 'สนพ.',
      plan: 'oil',
      status: 1,
    },
    {
      target: '304',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2568',
        endyear: '2573',
      },
      budget: 524085,
      own: 'สนพ.',
      plan: 'aedp',
      status: 0,
    },
    {
      target: '203',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2567',
        endyear: '2572',
      },
      budget: 1231286,
      own: 'ธพ.',
      plan: 'power',
      status: 0,
    },
    {
      target: '104',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2570',
        endyear: '2575',
      },
      budget: 636183,
      own: 'สกพ.',
      plan: 'power',
      status: 0,
    },
    {
      target: '104',
      name: 'เร่งรัดการสำรวจและผลิตก๊าซธรรมชาติในประเทศ',
      year: {
        startyear: '2567',
        endyear: '2576',
      },
      budget: 1185162,
      own: 'ธพ.',
      plan: 'oil',
      status: 0,
    },
    {
      target: '201',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2569',
        endyear: '2580',
      },
      budget: 1354324,
      own: 'สนพ.',
      plan: 'gas',
      status: 0,
    },
    {
      target: '104',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2568',
        endyear: '2576',
      },
      budget: 1393582,
      own: 'ชธ.',
      plan: 'oil',
      status: 1,
    },
    {
      target: '204',
      name: 'เร่งรัดการสำรวจและผลิตก๊าซธรรมชาติในประเทศ',
      year: {
        startyear: '2567',
        endyear: '2572',
      },
      budget: 221554,
      own: 'ชธ.',
      plan: 'gas',
      status: 2,
    },
    {
      target: '202',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2569',
        endyear: '2574',
      },
      budget: 1342561,
      own: 'ชธ.',
      plan: 'power',
      status: 0,
    },
    {
      target: '101',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2567',
        endyear: '2574',
      },
      budget: 607878,
      own: 'ธพ.',
      plan: 'gas',
      status: 1,
    },
    {
      target: '304',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2568',
        endyear: '2572',
      },
      budget: 1393624,
      own: 'สกพ.',
      plan: 'gas',
      status: 1,
    },
    {
      target: '303',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2568',
        endyear: '2579',
      },
      budget: 630359,
      own: 'ธพ.',
      plan: 'gas',
      status: 1,
    },
    {
      target: '204',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2569',
        endyear: '2577',
      },
      budget: 1484410,
      own: 'ชธ.',
      plan: 'power',
      status: 1,
    },
    {
      target: '104',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2570',
        endyear: '2575',
      },
      budget: 541864,
      own: 'ธพ.',
      plan: 'oil',
      status: 0,
    },
    {
      target: '203',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2568',
        endyear: '2572',
      },
      budget: 500228,
      own: 'ธพ.',
      plan: 'power',
      status: 2,
    },
    {
      target: '303',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2570',
        endyear: '2572',
      },
      budget: 1286932,
      own: 'สกพ.',
      plan: 'power',
      status: 2,
    },
    {
      target: '204',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2570',
        endyear: '2579',
      },
      budget: 830740,
      own: 'สกพ.',
      plan: 'power',
      status: 1,
    },
    {
      target: '204',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2569',
        endyear: '2575',
      },
      budget: 1107884,
      own: 'ธพ.',
      plan: 'power',
      status: 0,
    },
    {
      target: '102',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2570',
        endyear: '2574',
      },
      budget: 122075,
      own: 'ธพ.',
      plan: 'gas',
      status: 0,
    },
    {
      target: '301',
      name: 'เร่งรัดการสำรวจและผลิตก๊าซธรรมชาติในประเทศ',
      year: {
        startyear: '2570',
        endyear: '2578',
      },
      budget: 777753,
      own: 'สกพ.',
      plan: 'aedp',
      status: 2,
    },
    {
      target: '204',
      name: 'การเปิดให้ยื่นขอสิทธิสำรวจและผลิตปิโตเลียมรอบใหม่',
      year: {
        startyear: '2569',
        endyear: '2575',
      },
      budget: 1390906,
      own: 'ชธ.',
      plan: 'aedp',
      status: 0,
    },
    {
      target: '304',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2567',
        endyear: '2574',
      },
      budget: 1423451,
      own: 'ชธ.',
      plan: 'gas',
      status: 0,
    },
    {
      target: '301',
      name: 'การจัดหาไฟฟ้าตามแผนปฎิบัติการด้านไฟฟ้า (Power)',
      year: {
        startyear: '2567',
        endyear: '2579',
      },
      budget: 1213023,
      own: 'ชธ.',
      plan: 'gas',
      status: 2,
    },
    {
      target: '103',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2567',
        endyear: '2574',
      },
      budget: 1411188,
      own: 'สนพ.',
      plan: 'gas',
      status: 0,
    },
    {
      target: '103',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2568',
        endyear: '2577',
      },
      budget: 1258336,
      own: 'ธพ.',
      plan: 'gas',
      status: 0,
    },
    {
      target: '101',
      name: 'เร่งรัดการเจรจาในพื้นที่พัฒนาร่วมไทย-มาเลเซีย(JDA) และพื้นที่ไทยและกัมพูชาอ้างสิทธิในไหล่ทวิป',
      year: {
        startyear: '2570',
        endyear: '2577',
      },
      budget: 1431085,
      own: 'สนพ.',
      plan: 'oil',
      status: 2,
    },
  ];
  
  export default TargetProjectData;
  